MODEL:
  TYPE: shufflenet
  NUM_CLASSES: 1000
SHUFFLENET:
  MODEL_SIZE: 1.0x
  BLOCK_FUN: weightnet
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.125
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 4e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200
NUM_GPUS: 4
OUT_DIR: output/WeightNet_1x_imagenet_4gpu
